export const data = [
  {
    id: 1,
    platform: "Udemy",
    free_course: "yes",
    course_name: "Basic Python",
    link: "https://udemy.com/Basic-python",
    difficulty: "beginner",
    module_number: 6,
    certification: "free",
  },
  {
    id: 2,
    platform: "Udemy",
    free_course: "yes",
    course_name: "Basic C",
    link: "https://udemy.com/Basic-C",
    difficulty: "beginner",
    module_number: 7,
    certification: "paid",
  },
  {
    id: 3,
    platform: "Udemy",
    free_course: "no",
    course_name: "Python Bootcamp",
    link: "https://udemy.com/Basic-C",
    difficulty: "beginner",
    module_number: 23,
    certification: "paid",
  },
  {
    id: 4,
    platform: "Udemy",
    free_course: "no",
    course_name: "Build a Backend REST API with Node JS from Scratch",
    link: "https://www.udemy.com/course/build-backend-api-node-js-and-react-frontend/",
    difficulty: "beginner",
    module_number: 6,
    certification: "paid",
  },
  {
    id: 5,
    platform: "Udemy",
    free_course: "no",
    course_name: "machine learning",
    link: "https://www.udemy.com/course/machinelearning/",
    difficulty: "beginner",
    module_number: 6,
    certification: "paid",
  },
  {
    id: 6,
    platform: "Udemy",
    free_course: "no",
    course_name: "Data science",
    link: "https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/",
    difficulty: "beginner",
    module_number: 21,
    certification: "paid",
  },
  {
    id: 7,
    platform: "Udemy",
    free_course: "no",
    course_name: "Basic Python",
    link: "https://www.udemy.com/course/python-the-complete-python-developer-course/",
    difficulty: "beginner",
    module_number: 21,
    certification: "paid",
  },
  {
    id: 8,
    platform: "Udemy",
    free_course: "no",
    course_name: "Docker course",
    link: "https://www.udemy.com/course/docker-kubernetes-the-practical-guide/",
    difficulty: "beginner",
    module_number: 16,
    certification: "paid",
  },
  {
    id: 9,
    platform: "Udemy",
    free_course: "no",
    course_name: "Kubernets course",
    link: "https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/",
    difficulty: "beginner",
    module_number: 14,
    certification: "paid",
  },
  {
    id: 10,
    platform: "Udemy",
    free_course: "no",
    course_name: "Javascript",
    link: "https://www.udemy.com/course/the-complete-javascript-course/",
    difficulty: "beginner",
    module_number: 30,
    certification: "paid",
  },
  {
    id: 11,
    platform: "Udemy",
    free_course: "no",
    course_name: "Web Development",
    link: "https://www.udemy.com/course/the-complete-web-development-bootcamp/",
    difficulty: "beginner",
    module_number: 44,
    certification: "paid",
  },
  {
    id: 12,
    platform: "Udemy",
    free_course: "yes",
    course_name: "CSS",
    link: "https://www.udemy.com/course/design-and-develop-a-killer-website-with-html5-and-css3/",
    difficulty: "beginner",
    module_number: 32,
    certification: "paid",
  },
  {
    id: 13,
    platform: "Udemy",
    free_course: "no",
    course_name: "Ressponsive Websites",
    link: "https://www.udemy.com/course/design-and-develop-a-killer-website-with-html5-and-css3/",
    difficulty: "beginner",
    module_number: 21,
    certification: "paid",
  },
  {
    id: 14,
    platform: "Udemy",
    free_course: "yes",
    course_name: "Java Develepment",
    link: "https://www.udemy.com/course/design-and-develop-a-killer-website-with-html5-and-css3/",
    difficulty: "beginner",
    module_number: 11,
    certification: "paid",
  },
  {
    id: 15,
    platform: "Udemy",
    free_course: "no",
    course_name: "Java Programming Masterclass updated to Java 17",
    link: "https://www.udemy.com/course/java-the-complete-java-developer-course/",
    difficulty: "beginner",
    module_number: 46,
    certification: "paid",
  },
  {
    id: 16,
    platform: "Udemy",
    free_course: "no",
    course_name: "100 Days of Code: The Complete Python Pro Bootcamp for 2023",
    link: "https://www.udemy.com/course/100-days-of-code/",
    difficulty: "beginner",
    module_number: 101,
    certification: "paid",
  },
  {
    id: 17,
    platform: "Udemy",
    free_course: "no",
    course_name: "The Complete Python Bootcamp From Zero to Hero in Python",
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    difficulty: "beginner",
    module_number: 22,
    certification: "paid",
  },
  {
    id: 18,
    platform: "Udemy",
    free_course: "no",
    course_name: "Learn Perl 5 By Doing It",
    link: "https://www.udemy.com/course/perltutorial/",
    difficulty: "beginner",
    module_number: 14,
    certification: "paid",
  },
  {
    id: 19,
    platform: "Udemy",
    free_course: "no",
    course_name: "Machine Learning A-Z™: AI, Python & R + ChatGPT Bonus [2023]",
    link: "https://www.udemy.com/course/machinelearning/",
    difficulty: "moderate",
    module_number: 6,
    certification: "paid",
  },
  {
    id: 20,
    platform: "Udemy",
    free_course: "yes",
    course_name: "The Complete Python Bootcamp From Zero to Hero in Python",
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    difficulty: "beginner",
    module_number: 11,
    certification: "paid",
  },
  {
    id: 21,
    platform: "Udemy",
    free_course: "no",
    course_name: "Learn Phython Programming Masterclass",
    link: "https://www.udemy.com/course/python-the-complete-python-developer-course/",
    difficulty: "medium",
    module_number: 557,
    certification: "paid",
  },
  {
    id: 22,
    platform: "Udemy",
    free_course: "no",
    course_name: "Python for Beginners: Easy Python for Beginners Course",
    link: "https://www.udemy.com/course/python-in-a-weekend/",
    difficulty: "beginner",
    module_number: 9,
    certification: "paid",
  },
  {
    id: 23,
    platform: "Udemy",
    free_course: "yes",
    course_name: "The Complete 2023 Web Development Bootcamp",
    link: "ttps://www.udemy.com/course/the-complete-web-development-bootcamp/",
    difficulty: "intermediATE",
    module_number: 110,
    certification: "paid",
  },
  {
    id: 24,
    platform: "Udemy",
    free_course: "no",
    course_name: "Phython for beginners",
    link: "https://www.udemy.com/course/python-core-and-advanced/",
    difficulty: "beginner",
    module_number: 330,
    certification: "paid",
  },
  {
    id: 25,
    platform: "Udemy",
    free_course: "no",
    course_name: "Data Structures & Algorithms Essentials using C++ ",
    link: "https://www.udemy.com/course/cpp-data-structures-algorithms-prateek-narang/",
    difficulty: "Hard",
    module_number: 24,
    certification: "paid",
  },
  {
    id: 26,
    platform: "Udemy",
    free_course: "no",
    course_name: "Competitive Programming Essentials, Master Algorithms",
    link: "https://www.udemy.com/course/competitive-programming-algorithms-coding-minutes/",
    difficulty: "Advance",
    module_number: 168,
    certification: "paid",
  },
  {
    id: 27,
    platform: "Udemy",
    free_course: "no",
    course_name: "100 days of code",
    link: "https://www.udemy.com/course/100-days-of-code/",
    difficulty: "moderate",
    module_number: 101,
    certification: "paid",
  },
  {
    id: 28,
    platform: "Udemy",
    free_course: "no",
    course_name: "Unreal Engine 5: The Complete Beginner's Course",
    link: "https://www.udemy.com/course/unreal-engine-5-the-complete-beginners-course/pur",
    difficulty: "beginner",
    module_number: 79,
    certification: "paid",
  },
  {
    id: 29,
    platform: "Udemy",
    free_course: "no",
    course_name: "Python Network Programming for Network Engineers (Python 3)",
    link: "https://www.udemy.com/course/python-network-programming-for-network-engineers-python-3/",
    difficulty: "beginner",
    module_number: 171,
    certification: "paid",
  },
  {
    id: 30,
    platform: "Udemy",
    free_course: "no",
    course_name: "The Complete JavaScript Course 2023: From Zero to Expert!",
    link: "https://www.udemy.com/course/the-complete-javascript-course/",
    difficulty: "Beginner",
    module_number: 21,
    certification: "paid",
  },
  {
    id: 31,
    platform: "Udemy",
    free_course: "no",
    course_name: "Service Now",
    link: "https://www.udemy.com/course/servicenow-201-development/",
    difficulty: "beginner",
    module_number: 10,
    certification: "paid",
  },
  {
    id: 32,
    platform: "Udemy",
    free_course: "no",
    course_name: "Service Now master class",
    link: "https://www.udemy.com/course/servicenow-itsm-masterclass/",
    difficulty: "beginner",
    module_number: 11,
    certification: "paid",
  },
  {
    id: 33,
    platform: "Udemy",
    free_course: "yes",
    course_name: "Build Responsive Real-World Websites with HTML and CSS",
    link: "https://www.udemy.com/course/design-and-develop-a-killer-website-with-html5-and-css3/",
    difficulty: "beginner",
    module_number: 37,
    certification: "paid",
  },
  {
    id: 34,
    platform: "Udemy",
    free_course: "no",
    course_name: "The Complete 2023 Web Development Bootcamp",
    link: "https://www.udemy.com/course/the-complete-web-development-bootcamp/",
    difficulty: "beginner",
    module_number: 6,
    certification: "paid",
  },
  {
    id: 35,
    platform: "Udemy",
    free_course: "no",
    course_name: "100 Days of Code: The Complete Python Pro Bootcamp for 2023",
    link: "https://www.udemy.com/course/100-days-of-code/",
    difficulty: "beginner",
    module_number: 7,
    certification: "paid",
  },
  {
    id: 36,
    platform: "Udemy",
    free_course: "no",
    course_name: "Webdev",
    link: "https://www.udemy.com/course/webdev-criando-aplicacoes-para-web/",
    difficulty: "beginner",
    module_number: 11,
    certification: "paid",
  },
  {
    id: 37,
    platform: "Udemy",
    free_course: "no",
    course_name: "Basic C++",
    link: "https://www.udemy.com/course/c-plus-plus-programming-beginners/",
    difficulty: "beginner",
    module_number: 19.5,
    certification: "paid",
  },
  {
    id: 38,
    platform: "Udemy",
    free_course: "no",
    course_name: "amazon web services",
    link: "https://www.udemy.com/course/amazon-web-services-aws-v/",
    difficulty: "beginner",
    module_number: 19,
    certification: "unpaid",
  },
  {
    id: 39,
    platform: "Udemy",
    free_course: "no",
    course_name: "The Complete Cyber Security Course : Hackers ",
    link: "https://www.udemy.com/course/the-complete-internet-security-privacy-course-volume-1/",
    difficulty: "beginner",
    module_number: 12,
    certification: "paid",
  },
  {
    id: 40,
    platform: "Udemy",
    free_course: "no",
    course_name: "Leadership: Practical Leadership Skills",
    link: "https://www.udemy.com/course/practical-leadership/",
    difficulty: "beginner",
    module_number: 49,
    certification: "paid",
  },
  {
    id: 41,
    platform: "Udemy",
    free_course: "no",
    course_name: "The Science of Leadership",
    link: "https://www.udemy.com/course/neuromanagement/",
    difficulty: "beginner",
    module_number: 35,
    certification: "paid",
  },
  {
    id: 42,
    platform: "Udemy",
    free_course: "no",
    course_name: "Leadership Masterclass",
    link: "https://www.udemy.com/course/leadershipmasterclass/",
    difficulty: "beginner",
    module_number: 37,
    certification: "paid",
  },
  {
    id: 43,
    platform: "Udemy",
    free_course: "no",
    course_name: "Management Skills Training for New & Experienced Managers",
    link: "https://www.udemy.com/course/the-new-manager-managing-people-teams-processes/",
    difficulty: "beginner",
    module_number: 90,
    certification: "paid",
  },
  {
    id: 44,
    platform: "Udemy",
    free_course: "no",
    course_name: "Artificial intelligence boot camp",
    link: "https://www.udemy.com/course/10-code-less-days-of-artificial-intelligence/",
    difficulty: "beginner",
    module_number: 11,
    certification: "paid",
  },
  {
    id: 45,
    platform: "Udemy",
    free_course: "No",
    course_name: "Web Develepment",
    link: "https://www.udemy.com/course/the-complete-web-development-bootcamp/",
    difficulty: "beginner",
    module_number: 12,
    certification: "no",
  },
  {
    id: 46,
    platform: "Udemy",
    free_course: "yes",
    course_name: "Basic Python",
    link: "https://udemy.com/Basic-python",
    difficulty: "beginner",
    module_number: 9,
    certification: "free",
  },
  {
    id: 47,
    platform: "Udemy",
    free_course: "no",
    course_name: "Data science",
    link: "https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/",
    difficulty: "beginner",
    module_number: 21,
    certification: "paid",
  },
  {
    id: 48,
    platform: "Udemy",
    free_course: "no",
    course_name: "Java Script",
    link: "https://www.udemy.com/course/the-complete-web-development-bootcamp/",
    difficulty: "beginner",
    module_number: 44,
    certification: "paid",
  },
  {
    id: 49,
    platform: "Udemy",
    free_course: "no",
    course_name: "The Complete Python Bootcamp From Zero to Hero in Python",
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    difficulty: "beginner",
    module_number: 22,
    certification: "paid",
  },
  {
    id: 50,
    platform: "Udemy",
    free_course: "no",
    course_name: "Build Websites from Scratch with HTML & CSS",
    link: "https://www.udemy.com/course/build-website-scratch/",
    difficulty: "beginner",
    module_number: 81,
    certification: "paid",
  },
  {
    id: 51,
    platform: "Udemy",
    free_course: "no",
    course_name: "Leadership Complete Guide - Succeed in Management",
    link: "https://www.udemy.com/course/leadership-mastery/",
    difficulty: "beginner",
    module_number: 88,
    certification: "paid",
  },
  {
    id: 52,
    platform: "Udemy",
    free_course: "no",
    course_name: "Productivity and Time Management for the Overwhelmed",
    link: "https://www.udemy.com/course/productivity-and-time-management/",
    difficulty: "beginner",
    module_number: 101,
    certification: "paid",
  },
  {
    id: 53,
    platform: "Udemy",
    free_course: "no",
    course_name: "Mastering Data Structures & Algorithms using C and C++",
    link: "https://www.udemy.com/course/datastructurescncpp/",
    difficulty: "beginner",
    module_number: 123,
    certification: "paid",
  },
  {
    id: 54,
    platform: "Udemy",
    free_course: "no",
    course_name: "Bodyguarding, Close or Executive Protection (CP/EP)",
    link: "https://www.udemy.com/course/bodyguarding-close-or-executive-protection-cpep/",
    difficulty: "beginner",
    module_number: 108,
    certification: "paid",
  },
  {
    id: 55,
    platform: "Udemy",
    free_course: "no",
    course_name: "MongoDB - The Complete Developer's Guide 2023",
    link: "https://www.udemy.com/course/mongodb-the-complete-developers-guide/",
    difficulty: "beginner",
    module_number: 19,
    certification: "paid",
  },
  {
    id: 56,
    platform: "Udemy",
    free_course: "no",
    course_name: "MongoDB Database Developer Course In Python",
    link: "https://www.udemy.com/course/mongodb-database-developer-course-in-python/",
    difficulty: "beginner",
    module_number: 11,
    certification: "paid",
  },
  {
    id: 57,
    platform: "Udemy",
    free_course: "yes",
    course_name: "The Complete 2023 Web Development Bootcamp",
    link: "https://www.udemy.com/course/the-complete-web-development-bootcamp/",
    difficulty: "intermediate",
    module_number: 20,
    certification: "paid",
  },
  {
    id: 58,
    platform: "Udemy",
    free_course: "no",
    course_name: "Beginning of C++ Programming",
    link: "https://www.udemy.com/course/beginning-c-plus-plus-programming/",
    difficulty: "beginner",
    module_number: 305,
    certification: "paid",
  },
  {
    id: 59,
    platform: "Udemy",
    free_course: "no",
    course_name: "Complete SQL bootcamp",
    link: "https://www.udemy.com/course/the-complete-sql-bootcamp/",
    difficulty: "beginner",
    module_number: 83,
    certification: "paid",
  },
  {
    id: 60,
    platform: "Udemy",
    free_course: "no",
    course_name: "Unity Mobile Game Development",
    link: "https://www.udemy.com/course/unitymobilecourse/",
    difficulty: "beginner",
    module_number: 11,
    certification: "paid",
  },
  {
    id: 61,
    platform: "brave",
    free_course: "yes",
    course_name: "postman",
    link: "https://www.postman.com/downloads/postman-agent/",
    difficulty: "beginner",
    module_number: 8,
    certification: "free",
  },
  {
    id: 62,
    platform: "Udemy",
    free_course: "no",
    course_name: "The Complete Python Bootcamp From Zero to Hero in Python",
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    difficulty: "beginner",
    module_number: 15,
    certification: "paid",
  },
  {
    id: 63,
    platform: "Udemy",
    free_course: "no",
    course_name: "Java Web Services",
    link: "https://www.udemy.com/course/java-web-services/",
    difficulty: "beginner",
    module_number: 336,
    certification: "paid",
  },
  {
    id: 64,
    platform: "Udemy",
    free_course: "no",
    course_name: "The Science of Leadership",
    link: "https://www.udemy.com/course/neuromanagement/",
    difficulty: "beginner",
    module_number: 35,
    certification: "paid",
  },
  {
    id: 65,
    platform: "Udemy",
    free_course: "no",
    course_name: "Crash Course Electronics and PCB Design",
    link: "https://www.udemy.com/course/crash-course-electronics-and-pcb-design/",
    difficulty: "beginner",
    module_number: 159,
    certification: "paid",
  },
  {
    id: 66,
    platform: "Udemy",
    free_course: "no",
    course_name: "Statistics with R - Beginner Level",
    link: "https://www.udemy.com/course/statistics-with-r-beginner-level/",
    difficulty: "beginner",
    module_number: 46,
    certification: "paid",
  },
  {
    id: 67,
    platform: "Udemy",
    free_course: "no",
    course_name: "Statistics with R - Beginner Level",
    link: "https://www.udemy.com/course/statistics-with-r-beginner-level/",
    difficulty: "beginner",
    module_number: 48,
    certification: "paid",
  },
  {
    id: 68,
    platform: "Udemy",
    free_course: "no",
    course_name: "Adobe Photoshop",
    link: "https://www.udemy.com/course/adobe-photoshop-cc-for-complete-beginner-sinhala-medium/",
    difficulty: "beginner",
    module_number: 90,
    certification: "paid",
  },
  {
    id: 69,
    platform: "Udemy",
    free_course: "no",
    course_name: "Full Stack Web App in a Weekend",
    link: "https://www.udemy.com/course/full-stack-crash-course/",
    difficulty: "beginner",
    module_number: 71,
    certification: "paid",
  },
  {
    id: 70,
    platform: "Udemy",
    free_course: "no",
    course_name: "Webdev - Criando aplicações para Web",
    link: "https://www.udemy.com/course/webdev-criando-aplicacoes-para-web/",
    difficulty: "beginner",
    module_number: 150,
    certification: "paid",
  },
  {
    id: 71,
    platform: "Udemy",
    free_course: "no",
    course_name: "Flutter & Dart - The Complete Guide [2023 Edition]",
    link: "https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps/",
    difficulty: "beginner",
    module_number: 152,
    certification: "paid",
  },

  {
    id: 1,
    platform: "codecademy",
    free_course: "yes",
    course_name: "Learn HTML",
    link: "https://www.codecademy.com/learn/learn-html",
    difficulty: "beginner",
    module_number: 6,
    certification: "paid",
  },
  {
    id: 2,
    platform: "codecademy",
    free_course: "yes",
    course_name: "Learn Intermediate CSS",
    link: "https://www.codecademy.com/learn/learn-intermediate-css",
    difficulty: "intermediate",
    module_number: 10,
    certification: "paid",
  },
  {
    id: 3,
    platform: "codecademy",
    free_course: "yes",
    course_name: "How to Deploy a Website",
    link: "https://www.codecademy.com/learn/deploy-a-website",
    difficulty: "beginner",
    module_number: 3,
    certification: "paid",
  },
  {
    id: 4,
    platform: "codecademy",
    free_course: "yes",
    course_name: "Learn HTML: Forms",
    link: "https://www.codecademy.com/learn/learn-html-forms",
    difficulty: "beginner",
    module_number: 1,
    certification: "paid",
  },
  {
    id: 5,
    platform: "codecademy",
    free_course: "yes",
    course_name: "Intro to OpenAI GPT API",
    link: "https://www.codecademy.com/learn/intro-to-open-ai-gpt-api",
    difficulty: "beginner",
    module_number: 1,
    certification: "paid",
  },
  {
    id: 6,
    platform: "codecademy",
    free_course: "yes",
    course_name: "Learn MongoDB",
    link: "https://www.codecademy.com/learn/learn-mongodb",
    difficulty: "beginner",
    module_number: 15,
    certification: "paid",
  },
  {
    id: 7,
    platform: "codecademy",
    free_course: "yes",
    course_name: "Data Scientist: Natural Language Processing Specialist",
    link: "https://www.codecademy.com/learn/paths/data-science-nlp",
    difficulty: "beginner",
    module_number: 31,
    certification: "paid",
  },
  {
    id: 8,
    platform: "codecademy",
    free_course: "yes",
    course_name: "Intro to Machine Learning",
    link: "https://www.codecademy.com/learn/machine-learning",
    difficulty: "intermediate",
    module_number: 11,
    certification: "paid",
  },
  {
    id: 9,
    platform: "codecademy",
    free_course: "yes",
    course_name: "Build a Machine Learning Model with Python",
    link: "https://codecademy.com/learn/paths/machine-learning",
    difficulty: "intermediate",
    module_number: 11,
    certification: "paid",
  },
  {
    id: 10,
    platform: "codecademy",
    free_course: "no",
    course_name: "Learn Python 3",
    link: "https://www.codecademy.com/learn/learn-python-3",
    difficulty: "beginner",
    module_number: 13,
    certification: "free",
  },
  {
    id: 11,
    platform: "codecademy",
    free_course: "no",
    course_name: "Build Chatbots with Python",
    link: "https://www.codecademy.com/learn/paths/build-chatbots-with-python",
    difficulty: "beginner",
    module_number: 6,
    certification: "paid",
  },
  {
    id: 12,
    platform: "codecademy",
    free_course: "yes",
    course_name: "Intro to SQL",
    link: "https://www.codecademy.com/learn/intro-to-sql",
    difficulty: "beginner",
    module_number: 2,
    certification: "paid",
  },
  {
    id: 13,
    platform: "codecademy",
    free_course: "yes",
    course_name: "Learn JavaScript",
    link: "https://www.codecademy.com/learn/introduction-to-javascript",
    difficulty: "beginner",
    module_number: 11,
    certification: "free",
  },
  {
    id: 1,
    platform: "educative",
    free_course: "no",
    course_name: "Learn to code : Python for absolute beginners",
    link: "https://www.educative.io/courses/learn-to-code-python-for-absolute-beginners",
    difficulty: "beginners",
    module_number: 15,
    certification: "paid",
  },
  {
    id: 2,
    platform: "educative",
    free_course: "no",
    course_name: "Foundations of Linux ARM64: Debug, Disassemble, and Reverse",
    link: "https://www.educative.io/courses/foundations-of-linux-arm64-debug-disassemble-and-reverse",
    difficulty: "intermediate",
    module_number: 15,
    certification: "paid",
  },
  {
    id: 3,
    platform: "educative",
    free_course: "no",
    course_name: "Theory of computation",
    link: "https://www.educative.io/courses/theory-of-computations",
    difficulty: "beginner",
    module_number: 11,
    certification: "paid",
  },
  {
    id: 4,
    platform: "educative",
    free_course: "no",
    course_name: "Designing Machine/Deep Learning Models Using Azure CLI",
    link: "https://www.educative.io/courses/designing-machine-deep-learning-models-using-azure-cli",
    difficulty: "intermediate",
    module_number: 8,
    certification: "paid",
  },
  {
    id: 5,
    platform: "educative",
    free_course: "no",
    course_name: "Programming in python",
    link: "https://www.educative.io/courses/programming-in-python",
    difficulty: "beginner",
    module_number: 27,
    certification: "paid",
  },
  {
    id: 6,
    platform: "educative",
    free_course: "no",
    course_name: "The Art of PostgreSQL",
    link: "https://www.educative.io/courses/the-art-of-postgresql",
    difficulty: "advanced",
    module_number: 42,
    certification: "paid",
  },
  {
    id: 7,
    platform: "educative",
    free_course: "no",
    course_name: "Advanced Data Structures: Implementing Tries in C++ and Java",
    link: "https://www.educative.io/courses/advanced-data-structures-implementing-tries-in-cpp-and-java",
    difficulty: "intermediate",
    module_number: 10,
    certification: "paid",
  },
  {
    id: 8,
    platform: "educative",
    free_course: "no",
    course_name: "All About JUnit5",
    link: "https://www.educative.io/courses/all-about-junit5",
    difficulty: "beginner",
    module_number: 11,
    certification: "paid",
  },
  {
    id: 9,
    platform: "educative",
    free_course: "no",
    course_name: "Data Structures with Generic Types in Java",
    link: "https://www.educative.io/courses/data-structures-with-generic-types-in-java",
    difficulty: "intermediate",
    module_number: 15,
    certification: "paid",
  },
  {
    id: 10,
    platform: "educative",
    free_course: "no",
    course_name: "Learn to Code: Java for Absolute Beginners",
    link: "https://www.educative.io/courses/learn-to-code-java-for-absolute-beginners",
    difficulty: "beginner",
    module_number: 9,
    certification: "paid",
  },
  {
    id: 11,
    platform: "educative",
    free_course: "no",
    course_name: "Introduction to Data Analysis and Visualization with R",
    link: "https://www.educative.io/courses/introduction-to-data-analysis-and-visualization-with-r",
    difficulty: "beginner",
    module_number: 8,
    certification: "paid",
  },
  {
    id: 12,
    platform: "educative",
    free_course: "no",
    course_name:
      "Control Access to Your Applications Using Auth0 API in JavaScript",
    link: "https://www.educative.io/courses/control-access-to-your-apps-using-auth0-api-in-javascript",
    difficulty: "beginner",
    module_number: 8,
    certification: "paid",
  },
  {
    id: 13,
    platform: "educative",
    free_course: "no",
    course_name: "Building Full-Stack Web Applications With Node.js and React",
    link: "https://www.educative.io/courses/building-full-stack-web-applications-with-node-js-and-react",
    difficulty: "beginner",
    module_number: 10,
    certification: "paid",
  },
  {
    id: 14,
    platform: "educative",
    free_course: "no",
    course_name: "Integration with YouTube Data API in JavaScript",
    link: "https://www.educative.io/courses/integration-with-youtube-data-api-in-javascript",
    difficulty: "beginner",
    module_number: 8,
    certification: "paid",
  },
  {
    id: 15,
    platform: "educative",
    free_course: "no",
    course_name: "CI/CD Using Native Tools Available on AWS",
    link: "https://www.educative.io/courses/ci-cd-using-native-tools-available-on-aws",
    difficulty: "beginner",
    module_number: 8,
    certification: "paid",
  },
  {
    id: 16,
    platform: "educative",
    free_course: "no",
    course_name: "Software Design Patterns in C",
    link: "https://www.educative.io/courses/software-design-patterns-c",
    difficulty: "intermediate",
    module_number: 8,
    certification: "paid",
  },
  {
    id: 17,
    platform: "educative",
    free_course: "no",
    course_name:
      "Debugging, Disassembly & Reversing in Linux for x64 Architecture",
    link: "https://www.educative.io/courses/debugging-disassembly-reversing-in-linux-x64-architecture",
    difficulty: "intermediate",
    module_number: 15,
    certification: "paid",
  },
  {
    id: 18,
    platform: "educative",
    free_course: "no",
    course_name: "An In-Depth Understanding of Memory and Pointers in C",
    link: "https://www.educative.io/courses/in-depth-understanding-of-memory-and-pointers-in-c",
    difficulty: "beginner",
    module_number: 15,
    certification: "paid",
  },
  {
    id: 19,
    platform: "educative",
    free_course: "no",
    course_name: "Foundations of Linux ARM64: Debug, Disassemble, and Reverse",
    link: "https://www.educative.io/courses/foundations-of-linux-arm64-debug-disassemble-and-reverse",
    difficulty: "intermediate",
    module_number: 15,
    certification: "paid",
  },
  {
    id: 20,
    platform: "educative",
    free_course: "no",
    course_name: "Accelerated Linux Core Dump Analysis",
    link: "https://www.educative.io/courses/accelerated-linux-core-dump-analysis",
    difficulty: "advanced",
    module_number: 15,
    certification: "paid",
  },
  {
    id: 21,
    platform: "educative",
    free_course: "no",
    course_name: "Data Science in R: From Basics to Machine Learning",
    link: "https://www.educative.io/courses/data-science-in-r-from-basics-to-machine-learning",
    difficulty: "advanced",
    module_number: 11,
    certification: "paid",
  },
  {
    id: 22,
    platform: "educative",
    free_course: "no",
    course_name:
      "Getting Started with Mobile App Development with React Native",
    link: "https://www.educative.io/courses/getting-started-with-mobile-app-development-with-react-native",
    difficulty: "intermediate",
    module_number: 13,
    certification: "paid",
  },
  {
    id: 23,
    platform: "educative",
    free_course: "no",
    course_name: "Distributed Systems for Practitioners",
    link: "https://www.educative.io/courses/distributed-systems-practitioners",
    difficulty: "beginner",
    module_number: 31,
    certification: "paid",
  },
  {
    id: 24,
    platform: "educative",
    free_course: "no",
    course_name: "DevOps Katas: Mastering DevOps Practices",
    link: "https://www.educative.io/courses/devops-katas-mastering-devops-practices",
    difficulty: "advanced",
    module_number: 10,
    certification: "paid",
  },
  {
    id: 25,
    platform: "educative",
    free_course: "no",
    course_name: "A Practical Guide to Helm",
    link: "https://www.educative.io/courses/a-practical-guide-to-helm",
    difficulty: "intermediate",
    module_number: 9,
    certification: "paid",
  },
  {
    id: 26,
    platform: "educative",
    free_course: "no",
    course_name:
      "Mastering Artificial Intelligence with Azure Cognitive Services",
    link: "https://www.educative.io/courses/mastering-artificial-intelligence-azure-cognitive-services",
    difficulty: "intermediate",
    module_number: 17,
    certification: "paid",
  },
  {
    id: 27,
    platform: "educative",
    free_course: "no",
    course_name: "Automate Workflows with AWS Step Functions",
    link: "https://www.educative.io/courses/automate-workflows-with-aws-step-functions",
    difficulty: "beginner",
    module_number: 14,
    certification: "paid",
  },
  {
    id: 28,
    platform: "educative",
    free_course: "no",
    course_name: "AWS API Gateway: The Unsung Warrior",
    link: "https://www.educative.io/courses/aws-api-gateway-the-unsung-warrior",
    difficulty: "intermediate",
    module_number: 7,
    certification: "paid",
  },
  {
    id: 29,
    platform: "educative",
    free_course: "no",
    course_name: "The Definitive Guide to MongoDB",
    link: "https://www.educative.io/courses/definitive-guide-to-mongodb",
    difficulty: "intermediate",
    module_number: 7,
    certification: "paid",
  },
  {
    id: 30,
    platform: "educative",
    free_course: "no",
    course_name: "Beginning Node.js, Express & MongoDB Development",
    link: "https://www.educative.io/courses/beginning-nodejs-express-mongodb-development",
    difficulty: "intermediate",
    module_number: 6,
    certification: "paid",
  },
  {
    id: 31,
    platform: "educative",
    free_course: "no",
    course_name: "API Development in Go Using MongoDB",
    link: "https://www.educative.io/courses/api-development-in-go-using-mongodb",
    difficulty: "intermediate",
    module_number: 9,
    certification: "paid",
  },
  {
    id: 33,
    platform: "educative",
    free_course: "no",
    course_name: "MongoDB: The Complete Guide",
    link: "https://www.educative.io/courses/mongodb-complete-guide",
    difficulty: "intermediate",
    module_number: 7,
    certification: "paid",
  },
  {
    id: 34,
    platform: "educative",
    free_course: "no",
    course_name: "Building a WhatsApp Clone with Vue.js and AWS Amplify",
    link: "https://www.educative.io/courses/building-whatsapp-clone-with-vue-js-and-aws-amplify",
    difficulty: "intermediate",
    module_number: 7,
    certification: "paid",
  },
  {
    id: 35,
    platform: "educative",
    free_course: "no",
    course_name: "Vue - The Road to Enterprise",
    link: "https://www.educative.io/courses/vue-the-road-to-enterprise",
    difficulty: "advanced",
    module_number: 16,
    certification: "paid",
  },
  {
    id: 36,
    platform: "educative",
    free_course: "no",
    course_name: "Develop an E-Commerce App Using Java, Spring Boot and Vue.js",
    link: "https://www.educative.io/courses/develop-e-commerce-java-spring-boot-vue-js",
    difficulty: "intermediate",
    module_number: 12,
    certification: "paid",
  },
  {
    id: 37,
    platform: "educative",
    free_course: "no",
    course_name: "Building a Medium Clone With Vue 3",
    link: "https://www.educative.io/courses/medium-clone-vue3",
    difficulty: "beginner",
    module_number: 5,
    certification: "paid",
  },
  {
    id: 38,
    platform: "educative",
    free_course: "no",
    course_name: "The DevOps Toolkit Catalogue",
    link: "https://www.educative.io/courses/the-devops-toolkit-catalogue",
    difficulty: "intermediate",
    module_number: 17,
    certification: "paid",
  },
  {
    id: 39,
    platform: "educative",
    free_course: "no",
    course_name: "Beginner’s Guide to Terraform",
    link: "https://www.educative.io/courses/beginners-guide-to-terraform",
    difficulty: "beginner",
    module_number: 12,
    certification: "paid",
  },
  {
    id: 40,
    platform: "educative",
    free_course: "no",
    course_name: "HashiCorp Terraform Certified Associate Preparation Guide",
    link: "https://www.educative.io/courses/hashicorp-terraform-certified-associate-preparation-guide",
    difficulty: "intermediate",
    module_number: 17,
    certification: "paid",
  },
  {
    id: 41,
    platform: "educative",
    free_course: "no",
    course_name: "Kubernetes in Practice",
    link: "https://www.educative.io/courses/kubernetes-in-practice",
    difficulty: "beginner",
    module_number: 17,
    certification: "paid",
  },
  {
    id: 42,
    platform: "educative",
    free_course: "no",
    course_name: "Automate Your Network",
    link: "https://www.educative.io/courses/automate-your-network",
    difficulty: "intermediate",
    module_number: 13,
    certification: "paid",
  },
  {
    id: 43,
    platform: "educative",
    free_course: "no",
    course_name: "Quick Start Kubernetes",
    link: "https://www.educative.io/courses/quick-start-kubernetes",
    difficulty: "beginner",
    module_number: 6,
    certification: "paid",
  },
  {
    id: 44,
    platform: "educative",
    free_course: "no",
    course_name: "Terraform: From Beginner to Master with Examples in AWS",
    link: "https://www.educative.io/courses/terraform-beginner-master-aws",
    difficulty: "intermediate",
    module_number: 20,
    certification: "paid",
  },
  {
    id: 45,
    platform: "educative",
    free_course: "no",
    course_name: "Run Selenium Java Tests In Azure DevOps",
    link: "https://www.educative.io/courses/selenium-java-azure-devops",
    difficulty: "intermediate",
    module_number: 10,
    certification: "paid",
  },
  {
    id: 46,
    platform: "educative",
    free_course: "no",
    course_name: "Azure Data Studio Masterclass",
    link: "https://www.educative.io/courses/azure-data-studio-masterclass",
    difficulty: "Beginner",
    module_number: 11,
    certification: "paid",
  },
  {
    id: 47,
    platform: "educative",
    free_course: "no",
    course_name: "The Complete Guide to DevOps in Azure",
    link: "https://www.educative.io/courses/complete-guide-devops-azure",
    difficulty: "intermediate",
    module_number: 15,
    certification: "paid",
  },
  {
    id: 48,
    platform: "educative",
    free_course: "no",
    course_name: "Docker Deep Dive: Advanced Techniques",
    link: "https://www.educative.io/courses/advanced-docker-techniques",
    difficulty: "advanced",
    module_number: 10,
    certification: "paid",
  },
  {
    id: 49,
    platform: "educative",
    free_course: "no",
    course_name: "Docker for Web Developers",
    link: "https://www.educative.io/courses/docker-for-web-developers",
    difficulty: "beginner",
    module_number: 12,
    certification: "paid",
  },
  {
    id: 50,
    platform: "educative",
    free_course: "no",
    course_name: "Time Series Analysis with Python",
    link: "https://www.educative.io/courses/time-series-analysis-with-python",
    difficulty: "beginner",
    module_number: 8,
    certification: "paid",
  },
  {
    id: 51,
    platform: "educative",
    free_course: "no",
    course_name: "Testing React Applications with Postman and WebdriverIO",
    link: "https://www.educative.io/courses/testing-react-applications-with-postman-and-webdriver-io",
    difficulty: "beginner",
    module_number: 10,
    certification: "paid",
  },
  {
    id: 52,
    platform: "educative",
    free_course: "no",
    course_name:
      "Creating Payment Card Programs using Marqeta API in JavaScript",
    link: "https://www.educative.io/courses/handling-financial-services-with-square-api-in-javascript",
    difficulty: "beginner",
    module_number: 9,
    certification: "paid",
  },
  {
    id: 53,
    platform: "educative",
    free_course: "no",
    course_name: "Handling Financial Services with Square API in JavaScript",
    link: "https://www.educative.io/courses/handling-financial-services-with-square-api-in-javascript",
    difficulty: "advanced",
    module_number: 8,
    certification: "paid",
  },
  {
    id: 88,
    platform: "educative",
    free_course: "no",
    course_name: "Python 101: Interactively learn how to program with Python 3",
    link: "https://www.educative.io/courses/python-101-interactively-learn-how-to-program-with-python-3",
    difficulty: "beginner",
    module_number: 43,
    certification: "paid",
  },
  {
    id: 89,
    platform: "educative",
    free_course: "no",
    course_name: "Full Speed Python",
    link: "https://www.educative.io/courses/full-speed-python",
    difficulty: "beginner",
    module_number: 9,
    certification: "paid",
  },
  {
    id: 90,
    platform: "educative",
    free_course: "no",
    course_name:
      "Surfacing Video Data with the Dailymotion Data API in JavaScript",
    link: "https://www.educative.io/courses/surfacing-video-data-with-the-dailymotion-data-api-in-javascript",
    difficulty: "beginner",
    module_number: 7,
    certification: "paid",
  },
  {
    id: 91,
    platform: "educative",
    free_course: "no",
    course_name: "Animations in Angular",
    link: "https://www.educative.io/courses/animations-in-angular",
    difficulty: "Intermediate",
    module_number: 8,
    certification: "paid",
  },
  {
    id: 92,
    platform: "educative",
    free_course: "no",
    course_name: "Using fp-ts for Functional Programming in TypeScript",
    link: "https://www.educative.io/courses/using-fp-ts-for-functional-programming-in-typescript",
    difficulty: "Intermediate",
    module_number: 12,
    certification: "paid",
  },
  {
    id: 95,
    platform: "educative",
    free_course: "no",
    course_name: "A Complete Guide to Java Programming",
    link: "https://www.educative.io/courses/complete-guide-to-java-programming",
    difficulty: "Beginner",
    module_number: 14,
    certification: "paid",
  },
  {
    id: 98,
    platform: "educative",
    free_course: "no",
    course_name: "A Visual Introduction to Algorithms",
    link: "https://www.educative.io/courses/visual-introduction-to-algorithms",
    difficulty: "beginner",
    module_number: 8,
    certification: "paid",
  },
  {
    id: 99,
    platform: "educative",
    free_course: "no",
    course_name: " Python 3: An interactive deep dive",
    link: "https://www.educative.io/courses/python-3-an-interactive-deep-dive",
    difficulty: "beginner",
    module_number: 17,
    certification: "paid",
  },
  {
    id: 100,
    platform: "educative",
    free_course: "no",
    course_name: "Hands-on Vue.js: Build a fully functional SPA",
    link: "https://www.educative.io/courses/hands-on-vue-js-build-fully-functional-spa",
    difficulty: "beginner",
    module_number: 8,
    certification: "paid",
  },
  {
    id: 101,
    platform: "educative",
    free_course: "no",
    course_name: "Testing Vue.js Components with Jest",
    link: "https://www.educative.io/courses/testing-vuejs-components-with-jest",
    difficulty: "advanced",
    module_number: 10,
    certification: "paid",
  },
  {
    id: 106,
    platform: "educative",
    free_course: "no",
    course_name: "Getting Started with LINQ in C#",
    link: "https://www.educative.io/courses/getting-started-linq-c-sharp",
    difficulty: "intermediate",
    module_number: 7,
    certification: "paid",
  },
  {
    id: 107,
    platform: "educative",
    free_course: "no",
    course_name: "Mastering C# and .NET",
    link: "https://www.educative.io/courses/mastering-c-sharp-and-dotnet",
    difficulty: "beginner",
    module_number: 18,
    certification: "paid",
  },
  {
    id: 108,
    platform: "educative",
    free_course: "no",
    course_name: "C# Concurrency for Senior Engineering Interviews",
    link: "https://www.educative.io/courses/c-sharp-concurrency-for-senior-engineering-interviews",
    difficulty: "beginner",
    module_number: 5,
    certification: "paid",
  },
  {
    id: 109,
    platform: "educative",
    free_course: "no",
    course_name: "Learn to Code: C# for Absolute Beginners",
    link: "https://www.educative.io/courses/learn-to-code-c-sharp-for-absolute-beginners",
    difficulty: "beginner",
    module_number: 9,
    certification: "paid",
  },
  {
    id: 115,
    platform: "educative",
    free_course: "no",
    course_name: "React and GraphQL: Build an E-commerce App with Hygraph",
    link: "https://www.educative.io/courses/react-and-graphql-build-an-e-commerce-app-with-hygraph",
    difficulty: "Intermediate",
    module_number: 8,
    certification: "paid",
  },
  {
    id: 118,
    platform: "educative",
    free_course: "no",
    course_name:
      "Grokking Modern System Design Interview for Engineers & Managers",
    link: "https://www.educative.io/courses/grokking-modern-system-design-interview-for-engineers-managers",
    difficulty: "beginner",
    module_number: 40,
    certification: "paid",
  },
  {
    id: 125,
    platform: "educative",
    free_course: "no",
    course_name: "Mastering Algorithms for Problem Solving in C++",
    link: "https://www.educative.io/courses/mastering-algorithms-for-problem-solving-in-cpp",
    difficulty: "beginner",
    module_number: 7,
    certification: "paid",
  },
  {
    id: 126,
    platform: "educative",
    free_course: "no",
    course_name: "Marketing Analytics Using Machine Learning Techniques",
    link: "https://www.educative.io/courses/marketing-analytics-using-machine-learning-techniques",
    difficulty: "beginner",
    module_number: 7,
    certification: "paid",
  },
  {
    id: 127,
    platform: "educative",
    free_course: "no",
    course_name:
      "Data Structures Preliminaries (Refresher of Fundamentals in C++)",
    link: "https://www.educative.io/courses/data-structures-preliminaries-refresher-of-fundamentals-in-cpp",
    difficulty: "intermediate",
    module_number: 7,
    certification: "paid",
  },
  {
    id: 128,
    platform: "educative",
    free_course: "no",
    course_name: "AWS Cost Optimization",
    link: "https://www.educative.io/courses/aws-cost-optimization",
    difficulty: "intermediate",
    module_number: 7,
    certification: "paid",
  },
  {
    id: 129,
    platform: "educative",
    free_course: "no",
    course_name: "Blogging Using the Blogger API in Python",
    link: "https://www.educative.io/courses/blogger-api-python",
    difficulty: "beginner",
    module_number: 7,
    certification: "paid",
  },
  {
    id: 130,
    platform: "educative",
    free_course: "no",
    course_name: "Swift Programming for mobile app development",
    link: "https://www.educative.io/courses/swift-programming-mobile-app",
    difficulty: "beginner",
    module_number: 13,
    certification: "paid",
  },
  {
    id: 142,
    platform: "educative",
    free_course: "no",
    course_name: "Computing Matrix Algebra with R and Rcpp",
    link: "https://www.educative.io/courses/computing-matrix-algebra-with-r-and-rcpp",
    difficulty: "intermediate",
    module_number: 14,
    certification: "paid",
  },
  {
    id: 131,
    platform: "educative",
    free_course: "no",
    course_name: "Performing Modern Statistical Analysis with R",
    link: "https://www.educative.io/courses/performing-modern-statistical-analysis-r",
    difficulty: "intermediate",
    module_number: 18,
    certification: "paid",
  },
  {
    id: 133,
    platform: "educative",
    free_course: "no",
    course_name: "Using R for Data Analysis in Social Sciences",
    link: "https://www.educative.io/courses/using-r-data-analysis-social-sciences",
    difficulty: "intermediate",
    module_number: 11,
    certification: "paid",
  },
  {
    id: 132,
    platform: "educative",
    free_course: "no",
    course_name: "Game Data Science Using R",
    link: "https://www.educative.io/courses/game-data-science-using-r",
    difficulty: "intermediate",
    module_number: 15,
    certification: "paid",
  },
  {
    id: 135,
    platform: "educative",
    free_course: "no",
    course_name: "The Ultimate Guide to Rust Programming",
    link: "https://www.educative.io/courses/ultimate-guide-to-rust-programming",
    difficulty: "intermediate",
    module_number: 18,
    certification: "paid",
  },
  {
    id: 140,
    platform: "educative",
    free_course: "no",
    course_name: "Become a React Developer",
    link: "https://www.educative.io/path/become-a-react-developerata",
    difficulty: "Intermediate",
    module_number: 4,
    certification: "paid",
  },
  {
    id: 141,
    platform: "educative",
    free_course: "no",
    course_name: "Marketing Analytics Using Machine Learning Techniques",
    link: "https://www.educative.io/courses/marketing-analytics-using-machine-learning-techniques",
    difficulty: "Beginner",
    module_number: 7,
    certification: "paid",
  },
  {
    id: 142,
    platform: "educative",
    free_course: "no",
    course_name: "Infrastructure as Code Using Terraform",
    link: "https://www.educative.io/courses/infrastructure-as-code-using-terraform",
    difficulty: "Beginner",
    module_number: 7,
    certification: "paid",
  },
  {
    id: 144,
    platform: "educative",
    free_course: "no",
    course_name: "Prompt Engineering: Building a Professional Portfolio",
    link: "https://www.educative.io/courses/prompt-engineering-building-a-professional-portfolio",
    difficulty: "Beginner",
    module_number: 8,
    certification: "paid",
  },
  {
    id: 143,
    platform: "educative",
    free_course: "no",
    course_name: "Hands-On Quantum Machine Learning with Python",
    link: "https://www.educative.io/courses/hands-on-quantum-machine-learning-python",
    difficulty: "Advanced",
    module_number: 16,
    certification: "paid",
  },
  {
    id: 145,
    platform: "educative",
    free_course: "no",
    course_name: "Mastering Algorithms for Problem Solving in Java",
    link: "https://www.educative.io/courses/mastering-algorithms-for-problem-solving-in-java",
    difficulty: "Intermediate",
    module_number: 12,
    certification: "paid",
  },
];
